[project]
name = "amz-mcp"
version = "0.1.0"
description = "MCP server for fetching Amazon products"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "httpx"
]

[tool.poe.tasks]
serve = "uvicorn main:app --reload"
